/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Foyer_ESPRIT (void);
GtkWidget* create_Ajouter_Foyer (void);
GtkWidget* create_Modifier_Foyer (void);
GtkWidget* create_Supprimer_Foyer (void);
GtkWidget* create_Afficher_Foyer (void);
GtkWidget* create_Rechercher_Foyer (void);
