/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Foyer_ESPRIT (void);
GtkWidget* create_Ajouter_Foyer (void);
GtkWidget* create_Modifier_Foyer (void);
GtkWidget* create_Supprimer_Foyer (void);
GtkWidget* create_Afficher_Foyer (void);
GtkWidget* create_Rechercher_Foyer (void);
GtkWidget* create_gestiondesmenusdelasemaine (void);
GtkWidget* create_ajouterunmenu (void);
GtkWidget* create_rechercherunmenu (void);
GtkWidget* create_meilleurmenudelasemaine (void);
GtkWidget* create_supprimerunmenu (void);
GtkWidget* create_modifierunmenu (void);
GtkWidget* create_idajoutnondisponible (void);
GtkWidget* create_supprimererreur (void);
GtkWidget* create_verifierlamodification (void);
GtkWidget* create_modifiererreur (void);
