/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Foyer_ESPRIT (void)
{
  GtkWidget *Foyer_ESPRIT;
  GtkWidget *fixed1;
  GtkWidget *ADlabel1;
  GtkWidget *adbutton2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label26;
  GtkWidget *adbutton3;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label27;
  GtkWidget *adbutton1;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *adbuttonaff;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label25;
  GtkWidget *adbuttonchercher;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label32;

  Foyer_ESPRIT = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Foyer_ESPRIT), _("Foyer ESPRIT"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Foyer_ESPRIT), fixed1);

  ADlabel1 = gtk_label_new (_("Page Accueil"));
  gtk_widget_show (ADlabel1);
  gtk_fixed_put (GTK_FIXED (fixed1), ADlabel1, 112, 0);
  gtk_widget_set_size_request (ADlabel1, 152, 72);

  adbutton2 = gtk_button_new ();
  gtk_widget_show (adbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), adbutton2, 288, 168);
  gtk_widget_set_size_request (adbutton2, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (adbutton2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  adbutton3 = gtk_button_new ();
  gtk_widget_show (adbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), adbutton3, 144, 168);
  gtk_widget_set_size_request (adbutton3, 88, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (adbutton3), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox11), label27, FALSE, FALSE, 0);

  adbutton1 = gtk_button_new ();
  gtk_widget_show (adbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), adbutton1, 0, 168);
  gtk_widget_set_size_request (adbutton1, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (adbutton1), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  adbuttonaff = gtk_button_new ();
  gtk_widget_show (adbuttonaff);
  gtk_fixed_put (GTK_FIXED (fixed1), adbuttonaff, 64, 88);
  gtk_widget_set_size_request (adbuttonaff, 104, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (adbuttonaff), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  adbuttonchercher = gtk_button_new ();
  gtk_widget_show (adbuttonchercher);
  gtk_fixed_put (GTK_FIXED (fixed1), adbuttonchercher, 232, 88);
  gtk_widget_set_size_request (adbuttonchercher, 104, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (adbuttonchercher), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox16), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) adbutton2, "clicked",
                    G_CALLBACK (on_adbutton2_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbutton3, "clicked",
                    G_CALLBACK (on_adbutton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbutton1, "clicked",
                    G_CALLBACK (on_adbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbuttonaff, "clicked",
                    G_CALLBACK (on_adbuttonaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbuttonchercher, "clicked",
                    G_CALLBACK (on_adbuttonchercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Foyer_ESPRIT, Foyer_ESPRIT, "Foyer_ESPRIT");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, ADlabel1, "ADlabel1");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, adbutton2, "adbutton2");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, image10, "image10");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, label26, "label26");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, adbutton3, "adbutton3");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, image11, "image11");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, label27, "label27");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, adbutton1, "adbutton1");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, image12, "image12");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, label28, "label28");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, adbuttonaff, "adbuttonaff");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, image9, "image9");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, label25, "label25");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, adbuttonchercher, "adbuttonchercher");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, image16, "image16");
  GLADE_HOOKUP_OBJECT (Foyer_ESPRIT, label32, "label32");

  return Foyer_ESPRIT;
}

GtkWidget*
create_Ajouter_Foyer (void)
{
  GtkWidget *Ajouter_Foyer;
  GtkWidget *fixed2;
  GtkWidget *adentryNom1;
  GtkWidget *adentryPrenom1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *adentryID1;
  GtkObject *adspinbutton1_adj;
  GtkWidget *adspinbutton1;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *adcombobox1;
  GtkWidget *adradiobutton3;
  GSList *adradiobutton3_group = NULL;
  GtkWidget *adradiobutton2;
  GtkWidget *adradiobutton1;
  GtkWidget *adretour1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label17;
  GtkWidget *adbutton4;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label29;

  Ajouter_Foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Foyer), _("windowaj"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter_Foyer), fixed2);

  adentryNom1 = gtk_entry_new ();
  gtk_widget_show (adentryNom1);
  gtk_fixed_put (GTK_FIXED (fixed2), adentryNom1, 200, 16);
  gtk_widget_set_size_request (adentryNom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryNom1), 8226);

  adentryPrenom1 = gtk_entry_new ();
  gtk_widget_show (adentryPrenom1);
  gtk_fixed_put (GTK_FIXED (fixed2), adentryPrenom1, 200, 64);
  gtk_widget_set_size_request (adentryPrenom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryPrenom1), 8226);

  label1 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 16, 64);
  gtk_widget_set_size_request (label1, 80, 16);

  label2 = gtk_label_new (_("Niveau"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 16, 168);
  gtk_widget_set_size_request (label2, 72, 24);

  adentryID1 = gtk_entry_new ();
  gtk_widget_show (adentryID1);
  gtk_fixed_put (GTK_FIXED (fixed2), adentryID1, 200, 120);
  gtk_widget_set_size_request (adentryID1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryID1), 8226);

  adspinbutton1_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  adspinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (adspinbutton1_adj), 1, 0);
  gtk_widget_show (adspinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), adspinbutton1, 216, 168);
  gtk_widget_set_size_request (adspinbutton1, 60, 27);

  label3 = gtk_label_new (_("ID"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 24, 128);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("Numero de chambre"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 24, 280);
  gtk_widget_set_size_request (label4, 152, 24);

  label5 = gtk_label_new (_("Nom"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 24, 16);
  gtk_widget_set_size_request (label5, 40, 16);

  label6 = gtk_label_new (_("Bloc"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 0, 224);
  gtk_widget_set_size_request (label6, 88, 24);

  adcombobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (adcombobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), adcombobox1, 256, 280);
  gtk_widget_set_size_request (adcombobox1, 49, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (adcombobox1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adcombobox1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adcombobox1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adcombobox1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adcombobox1), _("5"));

  adradiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("C"));
  gtk_widget_show (adradiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), adradiobutton3, 384, 224);
  gtk_widget_set_size_request (adradiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (adradiobutton3), adradiobutton3_group);
  adradiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (adradiobutton3));

  adradiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("B"));
  gtk_widget_show (adradiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), adradiobutton2, 264, 224);
  gtk_widget_set_size_request (adradiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (adradiobutton2), adradiobutton3_group);
  adradiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (adradiobutton2));

  adradiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("A"));
  gtk_widget_show (adradiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), adradiobutton1, 136, 224);
  gtk_widget_set_size_request (adradiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (adradiobutton1), adradiobutton3_group);
  adradiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (adradiobutton1));

  adretour1 = gtk_button_new ();
  gtk_widget_show (adretour1);
  gtk_fixed_put (GTK_FIXED (fixed2), adretour1, 168, 328);
  gtk_widget_set_size_request (adretour1, 96, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (adretour1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox2), label17, FALSE, FALSE, 0);

  adbutton4 = gtk_button_new ();
  gtk_widget_show (adbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), adbutton4, 312, 328);
  gtk_widget_set_size_request (adbutton4, 96, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (adbutton4), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) adradiobutton3, "toggled",
                    G_CALLBACK (on_adradiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) adradiobutton2, "toggled",
                    G_CALLBACK (on_adradiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) adradiobutton1, "toggled",
                    G_CALLBACK (on_adradiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) adretour1, "clicked",
                    G_CALLBACK (on_adretour1_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbutton4, "clicked",
                    G_CALLBACK (on_adbutton4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Foyer, Ajouter_Foyer, "Ajouter_Foyer");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adentryNom1, "adentryNom1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adentryPrenom1, "adentryPrenom1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adentryID1, "adentryID1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adspinbutton1, "adspinbutton1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adcombobox1, "adcombobox1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adradiobutton3, "adradiobutton3");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adradiobutton2, "adradiobutton2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adradiobutton1, "adradiobutton1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adretour1, "adretour1");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, image2, "image2");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label17, "label17");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, adbutton4, "adbutton4");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, image13, "image13");
  GLADE_HOOKUP_OBJECT (Ajouter_Foyer, label29, "label29");

  return Ajouter_Foyer;
}

GtkWidget*
create_Modifier_Foyer (void)
{
  GtkWidget *Modifier_Foyer;
  GtkWidget *fixed3;
  GtkWidget *adentryNom2;
  GtkWidget *adentryprenom2;
  GtkWidget *adentryID2;
  GtkWidget *adentryNiveau2;
  GtkWidget *adentrychambre;
  GtkWidget *adentryBloc3;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label9;
  GtkWidget *label7;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *adbutton5;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label30;
  GtkWidget *adretour2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label18;

  Modifier_Foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_Foyer), _("windowmod"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modifier_Foyer), fixed3);

  adentryNom2 = gtk_entry_new ();
  gtk_widget_show (adentryNom2);
  gtk_fixed_put (GTK_FIXED (fixed3), adentryNom2, 184, 56);
  gtk_widget_set_size_request (adentryNom2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryNom2), 8226);

  adentryprenom2 = gtk_entry_new ();
  gtk_widget_show (adentryprenom2);
  gtk_fixed_put (GTK_FIXED (fixed3), adentryprenom2, 184, 88);
  gtk_widget_set_size_request (adentryprenom2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryprenom2), 8226);

  adentryID2 = gtk_entry_new ();
  gtk_widget_show (adentryID2);
  gtk_fixed_put (GTK_FIXED (fixed3), adentryID2, 184, 16);
  gtk_widget_set_size_request (adentryID2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryID2), 8226);

  adentryNiveau2 = gtk_entry_new ();
  gtk_widget_show (adentryNiveau2);
  gtk_fixed_put (GTK_FIXED (fixed3), adentryNiveau2, 184, 120);
  gtk_widget_set_size_request (adentryNiveau2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryNiveau2), 8226);

  adentrychambre = gtk_entry_new ();
  gtk_widget_show (adentrychambre);
  gtk_fixed_put (GTK_FIXED (fixed3), adentrychambre, 184, 200);
  gtk_widget_set_size_request (adentrychambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentrychambre), 8226);

  adentryBloc3 = gtk_entry_new ();
  gtk_widget_show (adentryBloc3);
  gtk_fixed_put (GTK_FIXED (fixed3), adentryBloc3, 184, 160);
  gtk_widget_set_size_request (adentryBloc3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryBloc3), 8226);

  label11 = gtk_label_new (_("Entrez ID "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 16, 24);
  gtk_widget_set_size_request (label11, 128, 16);

  label12 = gtk_label_new (_("Nouveau nom"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 24, 64);
  gtk_widget_set_size_request (label12, 112, 17);

  label9 = gtk_label_new (_("Nouveau niveau"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 24, 128);
  gtk_widget_set_size_request (label9, 120, 16);

  label7 = gtk_label_new (_("Nouveau N de chambre"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 8, 208);
  gtk_widget_set_size_request (label7, 176, 16);

  label10 = gtk_label_new (_("Nouveau bloc"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 16, 168);
  gtk_widget_set_size_request (label10, 120, 16);

  label8 = gtk_label_new (_("Nouveau prenom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 24, 96);
  gtk_widget_set_size_request (label8, 120, 17);

  adbutton5 = gtk_button_new ();
  gtk_widget_show (adbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), adbutton5, 264, 248);
  gtk_widget_set_size_request (adbutton5, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (adbutton5), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox14), label30, FALSE, FALSE, 0);

  adretour2 = gtk_button_new ();
  gtk_widget_show (adretour2);
  gtk_fixed_put (GTK_FIXED (fixed3), adretour2, 80, 248);
  gtk_widget_set_size_request (adretour2, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (adretour2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) adbutton5, "clicked",
                    G_CALLBACK (on_adbutton5_clicked),
                    NULL);
  g_signal_connect ((gpointer) adretour2, "clicked",
                    G_CALLBACK (on_adretour2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_Foyer, Modifier_Foyer, "Modifier_Foyer");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentryNom2, "adentryNom2");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentryprenom2, "adentryprenom2");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentryID2, "adentryID2");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentryNiveau2, "adentryNiveau2");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentrychambre, "adentrychambre");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adentryBloc3, "adentryBloc3");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label11, "label11");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label12, "label12");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label9, "label9");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label7, "label7");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label10, "label10");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label8, "label8");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adbutton5, "adbutton5");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, image14, "image14");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label30, "label30");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, adretour2, "adretour2");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, image3, "image3");
  GLADE_HOOKUP_OBJECT (Modifier_Foyer, label18, "label18");

  return Modifier_Foyer;
}

GtkWidget*
create_Supprimer_Foyer (void)
{
  GtkWidget *Supprimer_Foyer;
  GtkWidget *fixed4;
  GtkWidget *adentryNom4;
  GtkWidget *adretour3;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label19;
  GtkWidget *adbutton6;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label24;
  GtkWidget *adcheckbutton1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label31;
  GtkWidget *label14;

  Supprimer_Foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer_Foyer), _("windowsupp"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Supprimer_Foyer), fixed4);

  adentryNom4 = gtk_entry_new ();
  gtk_widget_show (adentryNom4);
  gtk_fixed_put (GTK_FIXED (fixed4), adentryNom4, 88, 88);
  gtk_widget_set_size_request (adentryNom4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentryNom4), 8226);

  adretour3 = gtk_button_new ();
  gtk_widget_show (adretour3);
  gtk_fixed_put (GTK_FIXED (fixed4), adretour3, 56, 184);
  gtk_widget_set_size_request (adretour3, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (adretour3), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  adbutton6 = gtk_button_new ();
  gtk_widget_show (adbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), adbutton6, 176, 184);
  gtk_widget_set_size_request (adbutton6, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (adbutton6), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox8), label24, FALSE, FALSE, 0);

  adcheckbutton1 = gtk_check_button_new ();
  gtk_widget_show (adcheckbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), adcheckbutton1, 104, 144);
  gtk_widget_set_size_request (adcheckbutton1, 118, 24);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (adcheckbutton1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("verification"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox15), label31, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Entrez ID a supprimer"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 40, 40);
  gtk_widget_set_size_request (label14, 248, 40);

  g_signal_connect ((gpointer) adretour3, "clicked",
                    G_CALLBACK (on_adretour3_clicked),
                    NULL);
  g_signal_connect ((gpointer) adbutton6, "clicked",
                    G_CALLBACK (on_adbutton6_clicked),
                    NULL);
  g_signal_connect ((gpointer) adcheckbutton1, "toggled",
                    G_CALLBACK (on_adcheckbutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_Foyer, Supprimer_Foyer, "Supprimer_Foyer");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, adentryNom4, "adentryNom4");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, adretour3, "adretour3");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, image4, "image4");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, label19, "label19");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, adbutton6, "adbutton6");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, image8, "image8");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, label24, "label24");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, adcheckbutton1, "adcheckbutton1");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, image15, "image15");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, label31, "label31");
  GLADE_HOOKUP_OBJECT (Supprimer_Foyer, label14, "label14");

  return Supprimer_Foyer;
}

GtkWidget*
create_Afficher_Foyer (void)
{
  GtkWidget *Afficher_Foyer;
  GtkWidget *fixed5;
  GtkWidget *adtreeview1;
  GtkWidget *label15;
  GtkWidget *adbuttonactualiser;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label16;
  GtkWidget *adretour4;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;

  Afficher_Foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher_Foyer), _("windowaff"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Afficher_Foyer), fixed5);

  adtreeview1 = gtk_tree_view_new ();
  gtk_widget_show (adtreeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), adtreeview1, 32, 40);
  gtk_widget_set_size_request (adtreeview1, 300, 200);

  label15 = gtk_label_new (_("LISTE DES ETUDIANTS"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed5), label15, 104, 0);
  gtk_widget_set_size_request (label15, 192, 48);

  adbuttonactualiser = gtk_button_new ();
  gtk_widget_show (adbuttonactualiser);
  gtk_fixed_put (GTK_FIXED (fixed5), adbuttonactualiser, 200, 256);
  gtk_widget_set_size_request (adbuttonactualiser, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (adbuttonactualiser), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox1), label16, FALSE, FALSE, 0);

  adretour4 = gtk_button_new ();
  gtk_widget_show (adretour4);
  gtk_fixed_put (GTK_FIXED (fixed5), adretour4, 64, 256);
  gtk_widget_set_size_request (adretour4, 112, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (adretour4), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) adtreeview1, "row_activated",
                    G_CALLBACK (on_adtreeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) adbuttonactualiser, "clicked",
                    G_CALLBACK (on_adbuttonactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) adretour4, "clicked",
                    G_CALLBACK (on_adretour4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher_Foyer, Afficher_Foyer, "Afficher_Foyer");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, adtreeview1, "adtreeview1");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, label15, "label15");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, adbuttonactualiser, "adbuttonactualiser");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, image1, "image1");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, label16, "label16");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, adretour4, "adretour4");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, image5, "image5");
  GLADE_HOOKUP_OBJECT (Afficher_Foyer, label20, "label20");

  return Afficher_Foyer;
}

GtkWidget*
create_Rechercher_Foyer (void)
{
  GtkWidget *Rechercher_Foyer;
  GtkWidget *fixed6;
  GtkWidget *adentry44;
  GtkWidget *adlabel7;
  GtkWidget *adbuttoncher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *adretour5;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;

  Rechercher_Foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Rechercher_Foyer), _("Rechercher Foyer"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Rechercher_Foyer), fixed6);

  adentry44 = gtk_entry_new ();
  gtk_widget_show (adentry44);
  gtk_fixed_put (GTK_FIXED (fixed6), adentry44, 120, 64);
  gtk_widget_set_size_request (adentry44, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adentry44), 8226);

  adlabel7 = gtk_label_new ("");
  gtk_widget_show (adlabel7);
  gtk_fixed_put (GTK_FIXED (fixed6), adlabel7, 128, 112);
  gtk_widget_set_size_request (adlabel7, 144, 72);

  adbuttoncher = gtk_button_new ();
  gtk_widget_show (adbuttoncher);
  gtk_fixed_put (GTK_FIXED (fixed6), adbuttoncher, 208, 200);
  gtk_widget_set_size_request (adbuttoncher, 136, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (adbuttoncher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  adretour5 = gtk_button_new ();
  gtk_widget_show (adretour5);
  gtk_fixed_put (GTK_FIXED (fixed6), adretour5, 64, 200);
  gtk_widget_set_size_request (adretour5, 128, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (adretour5), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) adbuttoncher, "clicked",
                    G_CALLBACK (on_adbuttoncher_clicked),
                    NULL);
  g_signal_connect ((gpointer) adretour5, "clicked",
                    G_CALLBACK (on_adretour5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Rechercher_Foyer, Rechercher_Foyer, "Rechercher_Foyer");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, adentry44, "adentry44");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, adlabel7, "adlabel7");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, adbuttoncher, "adbuttoncher");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, image6, "image6");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, label22, "label22");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, adretour5, "adretour5");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, image7, "image7");
  GLADE_HOOKUP_OBJECT (Rechercher_Foyer, label23, "label23");

  return Rechercher_Foyer;
}

GtkWidget*
create_gestiondesmenusdelasemaine (void)
{
  GtkWidget *gestiondesmenusdelasemaine;
  GtkWidget *fixed7;
  GtkWidget *treeviewmenu;
  GtkWidget *buttonactualisermenu;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label33;
  GtkWidget *ajouterunmenuacceuil;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label34;
  GtkWidget *rechercherunmenuacceuil;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label35;
  GtkWidget *button432_cm;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label36;
  GtkWidget *modifierunmenuacceuil;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label37;
  GtkWidget *supprimerunmenuacceuil;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label38;

  gestiondesmenusdelasemaine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestiondesmenusdelasemaine), _("Gestion des menus de la semaines"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (gestiondesmenusdelasemaine), fixed7);

  treeviewmenu = gtk_tree_view_new ();
  gtk_widget_show (treeviewmenu);
  gtk_fixed_put (GTK_FIXED (fixed7), treeviewmenu, 96, 72);
  gtk_widget_set_size_request (treeviewmenu, 396, 200);

  buttonactualisermenu = gtk_button_new ();
  gtk_widget_show (buttonactualisermenu);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonactualisermenu, 536, 80);
  gtk_widget_set_size_request (buttonactualisermenu, 112, 80);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonactualisermenu), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox17), label33, FALSE, FALSE, 0);

  ajouterunmenuacceuil = gtk_button_new ();
  gtk_widget_show (ajouterunmenuacceuil);
  gtk_fixed_put (GTK_FIXED (fixed7), ajouterunmenuacceuil, 72, 304);
  gtk_widget_set_size_request (ajouterunmenuacceuil, 216, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (ajouterunmenuacceuil), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Ajouter un menu "));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox18), label34, FALSE, FALSE, 0);

  rechercherunmenuacceuil = gtk_button_new ();
  gtk_widget_show (rechercherunmenuacceuil);
  gtk_fixed_put (GTK_FIXED (fixed7), rechercherunmenuacceuil, 72, 360);
  gtk_widget_set_size_request (rechercherunmenuacceuil, 218, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (rechercherunmenuacceuil), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Recherche d'un menu"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox19), label35, FALSE, FALSE, 0);

  button432_cm = gtk_button_new ();
  gtk_widget_show (button432_cm);
  gtk_fixed_put (GTK_FIXED (fixed7), button432_cm, 304, 304);
  gtk_widget_set_size_request (button432_cm, 128, 109);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button432_cm), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Meilleur menu"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox20), label36, FALSE, FALSE, 0);

  modifierunmenuacceuil = gtk_button_new ();
  gtk_widget_show (modifierunmenuacceuil);
  gtk_fixed_put (GTK_FIXED (fixed7), modifierunmenuacceuil, 448, 304);
  gtk_widget_set_size_request (modifierunmenuacceuil, 232, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (modifierunmenuacceuil), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Modifier un menu"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox21), label37, FALSE, FALSE, 0);

  supprimerunmenuacceuil = gtk_button_new ();
  gtk_widget_show (supprimerunmenuacceuil);
  gtk_fixed_put (GTK_FIXED (fixed7), supprimerunmenuacceuil, 448, 360);
  gtk_widget_set_size_request (supprimerunmenuacceuil, 232, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (supprimerunmenuacceuil), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Supprimer un menu"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox22), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewmenu, "row_activated",
                    G_CALLBACK (on_treeviewmenu_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonactualisermenu, "clicked",
                    G_CALLBACK (on_buttonactualisermenu_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterunmenuacceuil, "clicked",
                    G_CALLBACK (on_ajouterunmenuacceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercherunmenuacceuil, "clicked",
                    G_CALLBACK (on_rechercherunmenuacceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button432_cm, "clicked",
                    G_CALLBACK (on_button432_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierunmenuacceuil, "clicked",
                    G_CALLBACK (on_modifierunmenuacceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerunmenuacceuil, "clicked",
                    G_CALLBACK (on_supprimerunmenuacceuil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestiondesmenusdelasemaine, gestiondesmenusdelasemaine, "gestiondesmenusdelasemaine");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, treeviewmenu, "treeviewmenu");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, buttonactualisermenu, "buttonactualisermenu");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image17, "image17");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, ajouterunmenuacceuil, "ajouterunmenuacceuil");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image18, "image18");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, rechercherunmenuacceuil, "rechercherunmenuacceuil");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image19, "image19");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, button432_cm, "button432_cm");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image20, "image20");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, modifierunmenuacceuil, "modifierunmenuacceuil");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image21, "image21");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, supprimerunmenuacceuil, "supprimerunmenuacceuil");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, image22, "image22");
  GLADE_HOOKUP_OBJECT (gestiondesmenusdelasemaine, label38, "label38");

  return gestiondesmenusdelasemaine;
}

GtkWidget*
create_ajouterunmenu (void)
{
  GtkWidget *ajouterunmenu;
  GtkWidget *fixed8;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *entry13_cm;
  GtkWidget *entry2_cm;
  GtkWidget *entry1_cm;
  GtkObject *jourajoutcm_adj;
  GtkWidget *jourajoutcm;
  GtkObject *anneeajoutcm_adj;
  GtkWidget *anneeajoutcm;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label48;
  GtkWidget *moisajoutcm;
  GtkWidget *radiobutton3_cm;
  GSList *radiobutton3_cm_group = NULL;
  GtkWidget *radiobutton2_cm;
  GtkWidget *radiobutton1_cm;
  GtkWidget *buttonajouterafficher;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label46;
  GtkWidget *button4_cm;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label47;

  ajouterunmenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouterunmenu), _("Ajout d'un menu"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (ajouterunmenu), fixed8);

  label39 = gtk_label_new (_("Le type :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 152, 104);
  gtk_widget_set_size_request (label39, 152, 41);

  label40 = gtk_label_new (_("La date :"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed8), label40, 168, 312);
  gtk_widget_set_size_request (label40, 112, 32);

  entry13_cm = gtk_entry_new ();
  gtk_widget_show (entry13_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), entry13_cm, 296, 64);
  gtk_widget_set_size_request (entry13_cm, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13_cm), 8226);

  entry2_cm = gtk_entry_new ();
  gtk_widget_show (entry2_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), entry2_cm, 280, 200);
  gtk_widget_set_size_request (entry2_cm, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_cm), 8226);

  entry1_cm = gtk_entry_new ();
  gtk_widget_show (entry1_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), entry1_cm, 320, 256);
  gtk_widget_set_size_request (entry1_cm, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_cm), 8226);

  jourajoutcm_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jourajoutcm = gtk_spin_button_new (GTK_ADJUSTMENT (jourajoutcm_adj), 1, 0);
  gtk_widget_show (jourajoutcm);
  gtk_fixed_put (GTK_FIXED (fixed8), jourajoutcm, 248, 360);
  gtk_widget_set_size_request (jourajoutcm, 60, 27);

  anneeajoutcm_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  anneeajoutcm = gtk_spin_button_new (GTK_ADJUSTMENT (anneeajoutcm_adj), 1, 0);
  gtk_widget_show (anneeajoutcm);
  gtk_fixed_put (GTK_FIXED (fixed8), anneeajoutcm, 608, 360);
  gtk_widget_set_size_request (anneeajoutcm, 60, 27);

  label41 = gtk_label_new (_("Le contenu :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed8), label41, 152, 192);
  gtk_widget_set_size_request (label41, 128, 40);

  label42 = gtk_label_new (_("L'identifiant :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 128, 56);
  gtk_widget_set_size_request (label42, 176, 40);

  label43 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed8), label43, 160, 360);
  gtk_widget_set_size_request (label43, 113, 33);

  label44 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed8), label44, 328, 360);
  gtk_widget_set_size_request (label44, 64, 32);

  label45 = gtk_label_new (_("Annee :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed8), label45, 520, 360);
  gtk_widget_set_size_request (label45, 88, 33);

  label48 = gtk_label_new (_("La quantit\303\251 de d\303\251chets :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed8), label48, 136, 256);
  gtk_widget_set_size_request (label48, 200, 40);

  moisajoutcm = gtk_combo_box_new_text ();
  gtk_widget_show (moisajoutcm);
  gtk_fixed_put (GTK_FIXED (fixed8), moisajoutcm, 400, 360);
  gtk_widget_set_size_request (moisajoutcm, 112, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (moisajoutcm), _("Decembre"));

  radiobutton3_cm = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobutton3_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton3_cm, 480, 152);
  gtk_widget_set_size_request (radiobutton3_cm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3_cm), radiobutton3_cm_group);
  radiobutton3_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3_cm));

  radiobutton2_cm = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251jeuner"));
  gtk_widget_show (radiobutton2_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton2_cm, 328, 152);
  gtk_widget_set_size_request (radiobutton2_cm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_cm), radiobutton3_cm_group);
  radiobutton3_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_cm));

  radiobutton1_cm = gtk_radio_button_new_with_mnemonic (NULL, _("Petit d\303\251jeuner"));
  gtk_widget_show (radiobutton1_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton1_cm, 160, 152);
  gtk_widget_set_size_request (radiobutton1_cm, 140, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_cm), radiobutton3_cm_group);
  radiobutton3_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_cm));

  buttonajouterafficher = gtk_button_new ();
  gtk_widget_show (buttonajouterafficher);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonajouterafficher, 424, 464);
  gtk_widget_set_size_request (buttonajouterafficher, 176, 72);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonajouterafficher), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox23), label46, FALSE, FALSE, 0);

  button4_cm = gtk_button_new ();
  gtk_widget_show (button4_cm);
  gtk_fixed_put (GTK_FIXED (fixed8), button4_cm, 224, 464);
  gtk_widget_set_size_request (button4_cm, 162, 69);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button4_cm), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox24), label47, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton3_cm, "toggled",
                    G_CALLBACK (on_radiobutton3_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_cm, "toggled",
                    G_CALLBACK (on_radiobutton2_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_cm, "toggled",
                    G_CALLBACK (on_radiobutton1_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonajouterafficher, "clicked",
                    G_CALLBACK (on_buttonajouterafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_cm, "clicked",
                    G_CALLBACK (on_button4_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouterunmenu, ajouterunmenu, "ajouterunmenu");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label39, "label39");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label40, "label40");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, entry13_cm, "entry13_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, entry2_cm, "entry2_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, entry1_cm, "entry1_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, jourajoutcm, "jourajoutcm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, anneeajoutcm, "anneeajoutcm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label41, "label41");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label42, "label42");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label43, "label43");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label44, "label44");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label45, "label45");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label48, "label48");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, moisajoutcm, "moisajoutcm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, radiobutton3_cm, "radiobutton3_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, radiobutton2_cm, "radiobutton2_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, radiobutton1_cm, "radiobutton1_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, buttonajouterafficher, "buttonajouterafficher");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, image23, "image23");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label46, "label46");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, button4_cm, "button4_cm");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, image24, "image24");
  GLADE_HOOKUP_OBJECT (ajouterunmenu, label47, "label47");

  return ajouterunmenu;
}

GtkWidget*
create_rechercherunmenu (void)
{
  GtkWidget *rechercherunmenu;
  GtkWidget *fixed9;
  GtkWidget *entry777_cm;
  GtkWidget *label50;
  GtkWidget *sortierecherche_cm;
  GtkWidget *button111_cm;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label51;
  GtkWidget *button2222_cm;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label49;

  rechercherunmenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rechercherunmenu), _("Recherche d'un menu "));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (rechercherunmenu), fixed9);

  entry777_cm = gtk_entry_new ();
  gtk_widget_show (entry777_cm);
  gtk_fixed_put (GTK_FIXED (fixed9), entry777_cm, 320, 80);
  gtk_widget_set_size_request (entry777_cm, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry777_cm), 8226);

  label50 = gtk_label_new (_("Taper l'identifiant \303\240 rechercher:"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed9), label50, 88, 80);
  gtk_widget_set_size_request (label50, 225, 40);

  sortierecherche_cm = gtk_label_new ("");
  gtk_widget_show (sortierecherche_cm);
  gtk_fixed_put (GTK_FIXED (fixed9), sortierecherche_cm, 72, 136);
  gtk_widget_set_size_request (sortierecherche_cm, 616, 216);

  button111_cm = gtk_button_new ();
  gtk_widget_show (button111_cm);
  gtk_fixed_put (GTK_FIXED (fixed9), button111_cm, 504, 72);
  gtk_widget_set_size_request (button111_cm, 128, 40);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button111_cm), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox26), label51, FALSE, FALSE, 0);

  button2222_cm = gtk_button_new ();
  gtk_widget_show (button2222_cm);
  gtk_fixed_put (GTK_FIXED (fixed9), button2222_cm, 240, 368);
  gtk_widget_set_size_request (button2222_cm, 304, 56);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button2222_cm), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Retourner \303\240 la page d'acceuil"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox25), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button111_cm, "clicked",
                    G_CALLBACK (on_button111_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2222_cm, "clicked",
                    G_CALLBACK (on_button2222_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechercherunmenu, rechercherunmenu, "rechercherunmenu");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, entry777_cm, "entry777_cm");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, label50, "label50");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, sortierecherche_cm, "sortierecherche_cm");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, button111_cm, "button111_cm");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, image26, "image26");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, label51, "label51");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, button2222_cm, "button2222_cm");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, image25, "image25");
  GLADE_HOOKUP_OBJECT (rechercherunmenu, label49, "label49");

  return rechercherunmenu;
}

GtkWidget*
create_meilleurmenudelasemaine (void)
{
  GtkWidget *meilleurmenudelasemaine;
  GtkWidget *fixed10;
  GtkWidget *label52;
  GtkObject *spinbuttonmenu_cm_adj;
  GtkWidget *spinbuttonmenu_cm;
  GtkWidget *label63sortie_cm;
  GtkWidget *button44444_cm;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label54;
  GtkWidget *button234_cm;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label55;

  meilleurmenudelasemaine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (meilleurmenudelasemaine), _("Le meilleur menu de la semaine"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (meilleurmenudelasemaine), fixed10);

  label52 = gtk_label_new (_("Choisir le jour indiquant le d\303\251but de la semaine :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed10), label52, 72, 88);
  gtk_widget_set_size_request (label52, 336, 40);

  spinbuttonmenu_cm_adj = gtk_adjustment_new (1, 1, 22, 1, 10, 10);
  spinbuttonmenu_cm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmenu_cm_adj), 1, 0);
  gtk_widget_show (spinbuttonmenu_cm);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbuttonmenu_cm, 416, 96);
  gtk_widget_set_size_request (spinbuttonmenu_cm, 60, 27);

  label63sortie_cm = gtk_label_new ("");
  gtk_widget_show (label63sortie_cm);
  gtk_fixed_put (GTK_FIXED (fixed10), label63sortie_cm, 24, 184);
  gtk_widget_set_size_request (label63sortie_cm, 560, 104);

  button44444_cm = gtk_button_new ();
  gtk_widget_show (button44444_cm);
  gtk_fixed_put (GTK_FIXED (fixed10), button44444_cm, 112, 328);
  gtk_widget_set_size_request (button44444_cm, 256, 64);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button44444_cm), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Trouver le meilleur menu"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox27), label54, FALSE, FALSE, 0);

  button234_cm = gtk_button_new ();
  gtk_widget_show (button234_cm);
  gtk_fixed_put (GTK_FIXED (fixed10), button234_cm, 400, 328);
  gtk_widget_set_size_request (button234_cm, 136, 64);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button234_cm), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox28), label55, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button44444_cm, "clicked",
                    G_CALLBACK (on_button44444_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) button234_cm, "clicked",
                    G_CALLBACK (on_button234_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (meilleurmenudelasemaine, meilleurmenudelasemaine, "meilleurmenudelasemaine");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, label52, "label52");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, spinbuttonmenu_cm, "spinbuttonmenu_cm");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, label63sortie_cm, "label63sortie_cm");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, button44444_cm, "button44444_cm");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, image27, "image27");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, label54, "label54");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, button234_cm, "button234_cm");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, image28, "image28");
  GLADE_HOOKUP_OBJECT (meilleurmenudelasemaine, label55, "label55");

  return meilleurmenudelasemaine;
}

GtkWidget*
create_supprimerunmenu (void)
{
  GtkWidget *supprimerunmenu;
  GtkWidget *fixed11;
  GtkWidget *label56;
  GtkWidget *entry3333_cm;
  GtkWidget *button7_cm;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label58;
  GtkWidget *checkbutton3_cm;
  GtkWidget *buttonsupprimerafficher;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label57;

  supprimerunmenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimerunmenu), _("Suppression d'un menu"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (supprimerunmenu), fixed11);

  label56 = gtk_label_new (_("Choisir l'identifiant du menu \303\240 supprimer :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 112, 64);
  gtk_widget_set_size_request (label56, 336, 64);

  entry3333_cm = gtk_entry_new ();
  gtk_widget_show (entry3333_cm);
  gtk_fixed_put (GTK_FIXED (fixed11), entry3333_cm, 432, 72);
  gtk_widget_set_size_request (entry3333_cm, 296, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3333_cm), 8226);

  button7_cm = gtk_button_new ();
  gtk_widget_show (button7_cm);
  gtk_fixed_put (GTK_FIXED (fixed11), button7_cm, 208, 208);
  gtk_widget_set_size_request (button7_cm, 200, 64);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button7_cm), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox30), label58, FALSE, FALSE, 0);

  checkbutton3_cm = gtk_check_button_new_with_mnemonic (_("Je confirme la suppression de ce menu "));
  gtk_widget_show (checkbutton3_cm);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton3_cm, 280, 152);
  gtk_widget_set_size_request (checkbutton3_cm, 312, 24);

  buttonsupprimerafficher = gtk_button_new ();
  gtk_widget_show (buttonsupprimerafficher);
  gtk_fixed_put (GTK_FIXED (fixed11), buttonsupprimerafficher, 432, 208);
  gtk_widget_set_size_request (buttonsupprimerafficher, 192, 64);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (buttonsupprimerafficher), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox29), label57, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button7_cm, "clicked",
                    G_CALLBACK (on_button7_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3_cm, "toggled",
                    G_CALLBACK (on_checkbutton3_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimerafficher, "clicked",
                    G_CALLBACK (on_buttonsupprimerafficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimerunmenu, supprimerunmenu, "supprimerunmenu");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, label56, "label56");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, entry3333_cm, "entry3333_cm");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, button7_cm, "button7_cm");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, image30, "image30");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, label58, "label58");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, checkbutton3_cm, "checkbutton3_cm");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, buttonsupprimerafficher, "buttonsupprimerafficher");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, image29, "image29");
  GLADE_HOOKUP_OBJECT (supprimerunmenu, label57, "label57");

  return supprimerunmenu;
}

GtkWidget*
create_modifierunmenu (void)
{
  GtkWidget *modifierunmenu;
  GtkWidget *fixed12;
  GtkWidget *label59;
  GtkWidget *entry111_cm;
  GtkWidget *label60;
  GtkWidget *entry444_cm;
  GtkWidget *entry222_cm;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkObject *spinbutton55_cm_adj;
  GtkWidget *spinbutton55_cm;
  GtkObject *spinbutton66_cm_adj;
  GtkWidget *spinbutton66_cm;
  GtkWidget *label66;
  GtkWidget *combobox111_cm;
  GtkWidget *radiobutton13_cm;
  GSList *radiobutton13_cm_group = NULL;
  GtkWidget *radiobutton11_cm;
  GtkWidget *radiobutton12_cm;
  GtkWidget *button6_cm;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label67;
  GtkWidget *buttonmodifierafficher;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image32;
  GtkWidget *label68;

  modifierunmenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifierunmenu), _("Modification d'un menu"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (modifierunmenu), fixed12);

  label59 = gtk_label_new (_("L'identifiant :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed12), label59, 120, 80);
  gtk_widget_set_size_request (label59, 129, 80);

  entry111_cm = gtk_entry_new ();
  gtk_widget_show (entry111_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), entry111_cm, 240, 104);
  gtk_widget_set_size_request (entry111_cm, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry111_cm), 8226);

  label60 = gtk_label_new (_("Le type :"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed12), label60, 120, 176);
  gtk_widget_set_size_request (label60, 112, 32);

  entry444_cm = gtk_entry_new ();
  gtk_widget_show (entry444_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), entry444_cm, 232, 264);
  gtk_widget_set_size_request (entry444_cm, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry444_cm), 8226);

  entry222_cm = gtk_entry_new ();
  gtk_widget_show (entry222_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), entry222_cm, 320, 312);
  gtk_widget_set_size_request (entry222_cm, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry222_cm), 8226);

  label61 = gtk_label_new (_("Le contenu :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed12), label61, 136, 256);
  gtk_widget_set_size_request (label61, 97, 48);

  label62 = gtk_label_new (_("La quantit\303\251 de d\303\251chets  :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed12), label62, 136, 304);
  gtk_widget_set_size_request (label62, 184, 48);

  label63 = gtk_label_new (_("La date :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed12), label63, 144, 384);
  gtk_widget_set_size_request (label63, 129, 32);

  label64 = gtk_label_new (_("Jour"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed12), label64, 208, 456);
  gtk_widget_set_size_request (label64, 49, 17);

  label65 = gtk_label_new (_("Annee"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed12), label65, 520, 456);
  gtk_widget_set_size_request (label65, 49, 17);

  spinbutton55_cm_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton55_cm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton55_cm_adj), 1, 0);
  gtk_widget_show (spinbutton55_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton55_cm, 264, 448);
  gtk_widget_set_size_request (spinbutton55_cm, 60, 27);

  spinbutton66_cm_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  spinbutton66_cm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton66_cm_adj), 1, 0);
  gtk_widget_show (spinbutton66_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton66_cm, 576, 448);
  gtk_widget_set_size_request (spinbutton66_cm, 60, 27);

  label66 = gtk_label_new (_("Mois"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed12), label66, 352, 456);
  gtk_widget_set_size_request (label66, 49, 17);

  combobox111_cm = gtk_combo_box_new_text ();
  gtk_widget_show (combobox111_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox111_cm, 408, 448);
  gtk_widget_set_size_request (combobox111_cm, 96, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox111_cm), _("Decembre"));

  radiobutton13_cm = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobutton13_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton13_cm, 432, 216);
  gtk_widget_set_size_request (radiobutton13_cm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13_cm), radiobutton13_cm_group);
  radiobutton13_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13_cm));

  radiobutton11_cm = gtk_radio_button_new_with_mnemonic (NULL, _("Petit d\303\251jeuner"));
  gtk_widget_show (radiobutton11_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton11_cm, 144, 216);
  gtk_widget_set_size_request (radiobutton11_cm, 132, 24);
  gtk_button_set_focus_on_click (GTK_BUTTON (radiobutton11_cm), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11_cm), radiobutton13_cm_group);
  radiobutton13_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11_cm));

  radiobutton12_cm = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251jeuner"));
  gtk_widget_show (radiobutton12_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton12_cm, 296, 216);
  gtk_widget_set_size_request (radiobutton12_cm, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12_cm), radiobutton13_cm_group);
  radiobutton13_cm_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12_cm));

  button6_cm = gtk_button_new ();
  gtk_widget_show (button6_cm);
  gtk_fixed_put (GTK_FIXED (fixed12), button6_cm, 224, 528);
  gtk_widget_set_size_request (button6_cm, 152, 48);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button6_cm), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox31), label67, FALSE, FALSE, 0);

  buttonmodifierafficher = gtk_button_new ();
  gtk_widget_show (buttonmodifierafficher);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonmodifierafficher, 408, 528);
  gtk_widget_set_size_request (buttonmodifierafficher, 136, 45);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (buttonmodifierafficher), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image32 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox32), image32, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox32), label68, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton13_cm, "toggled",
                    G_CALLBACK (on_radiobutton13_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11_cm, "toggled",
                    G_CALLBACK (on_radiobutton11_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton12_cm, "toggled",
                    G_CALLBACK (on_radiobutton12_cm_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6_cm, "clicked",
                    G_CALLBACK (on_button6_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifierafficher, "clicked",
                    G_CALLBACK (on_buttonmodifierafficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifierunmenu, modifierunmenu, "modifierunmenu");
  GLADE_HOOKUP_OBJECT (modifierunmenu, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label59, "label59");
  GLADE_HOOKUP_OBJECT (modifierunmenu, entry111_cm, "entry111_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label60, "label60");
  GLADE_HOOKUP_OBJECT (modifierunmenu, entry444_cm, "entry444_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, entry222_cm, "entry222_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label61, "label61");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label62, "label62");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label63, "label63");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label64, "label64");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label65, "label65");
  GLADE_HOOKUP_OBJECT (modifierunmenu, spinbutton55_cm, "spinbutton55_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, spinbutton66_cm, "spinbutton66_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label66, "label66");
  GLADE_HOOKUP_OBJECT (modifierunmenu, combobox111_cm, "combobox111_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, radiobutton13_cm, "radiobutton13_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, radiobutton11_cm, "radiobutton11_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, radiobutton12_cm, "radiobutton12_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, button6_cm, "button6_cm");
  GLADE_HOOKUP_OBJECT (modifierunmenu, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (modifierunmenu, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (modifierunmenu, image31, "image31");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label67, "label67");
  GLADE_HOOKUP_OBJECT (modifierunmenu, buttonmodifierafficher, "buttonmodifierafficher");
  GLADE_HOOKUP_OBJECT (modifierunmenu, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (modifierunmenu, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (modifierunmenu, image32, "image32");
  GLADE_HOOKUP_OBJECT (modifierunmenu, label68, "label68");

  return modifierunmenu;
}

GtkWidget*
create_idajoutnondisponible (void)
{
  GtkWidget *idajoutnondisponible;
  GtkWidget *fixed13;
  GtkWidget *label70;
  GtkWidget *button7777_cm;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image33;
  GtkWidget *label69;

  idajoutnondisponible = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (idajoutnondisponible), _("ID invalide"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (idajoutnondisponible), fixed13);

  label70 = gtk_label_new (_("Cet identifiant correspond d\303\251j\303\240 \303\240 un autre menu."));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed13), label70, 24, 32);
  gtk_widget_set_size_request (label70, 496, 120);

  button7777_cm = gtk_button_new ();
  gtk_widget_show (button7777_cm);
  gtk_fixed_put (GTK_FIXED (fixed13), button7777_cm, 168, 144);
  gtk_widget_set_size_request (button7777_cm, 192, 56);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button7777_cm), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image33 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox33), image33, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Retourner "));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox33), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button7777_cm, "clicked",
                    G_CALLBACK (on_button7777_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (idajoutnondisponible, idajoutnondisponible, "idajoutnondisponible");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, label70, "label70");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, button7777_cm, "button7777_cm");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, image33, "image33");
  GLADE_HOOKUP_OBJECT (idajoutnondisponible, label69, "label69");

  return idajoutnondisponible;
}

GtkWidget*
create_supprimererreur (void)
{
  GtkWidget *supprimererreur;
  GtkWidget *fixed14;
  GtkWidget *label71;
  GtkWidget *button200_cm;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image34;
  GtkWidget *label72;

  supprimererreur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimererreur), _("Erreur"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (supprimererreur), fixed14);

  label71 = gtk_label_new (_("Cet identifiant ne correspond \303\240 aucun menu!"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed14), label71, 40, 24);
  gtk_widget_set_size_request (label71, 320, 120);

  button200_cm = gtk_button_new ();
  gtk_widget_show (button200_cm);
  gtk_fixed_put (GTK_FIXED (fixed14), button200_cm, 112, 152);
  gtk_widget_set_size_request (button200_cm, 168, 64);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button200_cm), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image34 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox34), image34, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox34), label72, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button200_cm, "clicked",
                    G_CALLBACK (on_button200_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimererreur, supprimererreur, "supprimererreur");
  GLADE_HOOKUP_OBJECT (supprimererreur, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (supprimererreur, label71, "label71");
  GLADE_HOOKUP_OBJECT (supprimererreur, button200_cm, "button200_cm");
  GLADE_HOOKUP_OBJECT (supprimererreur, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (supprimererreur, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (supprimererreur, image34, "image34");
  GLADE_HOOKUP_OBJECT (supprimererreur, label72, "label72");

  return supprimererreur;
}

GtkWidget*
create_verifierlamodification (void)
{
  GtkWidget *verifierlamodification;
  GtkWidget *fixed15;
  GtkWidget *entryverifmodif_cm;
  GtkWidget *label73;
  GtkWidget *buttonmodifierverif_cm;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image35;
  GtkWidget *label74;
  GtkWidget *buttonretour_cm;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image37;
  GtkWidget *label77;

  verifierlamodification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (verifierlamodification), _("Choisir l'identifiant du menu \303\240 modifier"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (verifierlamodification), fixed15);

  entryverifmodif_cm = gtk_entry_new ();
  gtk_widget_show (entryverifmodif_cm);
  gtk_fixed_put (GTK_FIXED (fixed15), entryverifmodif_cm, 448, 88);
  gtk_widget_set_size_request (entryverifmodif_cm, 160, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryverifmodif_cm), 8226);

  label73 = gtk_label_new (_("Taper l'identifiant du menu que vous voulez modifier :"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed15), label73, 56, 88);
  gtk_widget_set_size_request (label73, 384, 40);

  buttonmodifierverif_cm = gtk_button_new ();
  gtk_widget_show (buttonmodifierverif_cm);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonmodifierverif_cm, 160, 152);
  gtk_widget_set_size_request (buttonmodifierverif_cm, 152, 56);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (buttonmodifierverif_cm), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image35 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox35), image35, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Modifier ce menu "));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox35), label74, FALSE, FALSE, 0);

  buttonretour_cm = gtk_button_new ();
  gtk_widget_show (buttonretour_cm);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonretour_cm, 328, 152);
  gtk_widget_set_size_request (buttonretour_cm, 152, 56);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (buttonretour_cm), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image37 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox37), image37, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox37), label77, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonmodifierverif_cm, "clicked",
                    G_CALLBACK (on_buttonmodifierverif_cm_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretour_cm, "clicked",
                    G_CALLBACK (on_buttonretour_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (verifierlamodification, verifierlamodification, "verifierlamodification");
  GLADE_HOOKUP_OBJECT (verifierlamodification, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (verifierlamodification, entryverifmodif_cm, "entryverifmodif_cm");
  GLADE_HOOKUP_OBJECT (verifierlamodification, label73, "label73");
  GLADE_HOOKUP_OBJECT (verifierlamodification, buttonmodifierverif_cm, "buttonmodifierverif_cm");
  GLADE_HOOKUP_OBJECT (verifierlamodification, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (verifierlamodification, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (verifierlamodification, image35, "image35");
  GLADE_HOOKUP_OBJECT (verifierlamodification, label74, "label74");
  GLADE_HOOKUP_OBJECT (verifierlamodification, buttonretour_cm, "buttonretour_cm");
  GLADE_HOOKUP_OBJECT (verifierlamodification, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (verifierlamodification, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (verifierlamodification, image37, "image37");
  GLADE_HOOKUP_OBJECT (verifierlamodification, label77, "label77");

  return verifierlamodification;
}

GtkWidget*
create_modifiererreur (void)
{
  GtkWidget *modifiererreur;
  GtkWidget *fixed16;
  GtkWidget *label75;
  GtkWidget *button244_cm;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image36;
  GtkWidget *label76;

  modifiererreur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifiererreur), _("Menu inexistant"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (modifiererreur), fixed16);

  label75 = gtk_label_new (_("L'dentifiant que vous avez tapez ne correspond \303\240 aucun menu !"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed16), label75, 96, 32);
  gtk_widget_set_size_request (label75, 432, 104);

  button244_cm = gtk_button_new ();
  gtk_widget_show (button244_cm);
  gtk_fixed_put (GTK_FIXED (fixed16), button244_cm, 240, 136);
  gtk_widget_set_size_request (button244_cm, 176, 56);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (button244_cm), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image36 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox36), image36, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox36), label76, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button244_cm, "clicked",
                    G_CALLBACK (on_button244_cm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifiererreur, modifiererreur, "modifiererreur");
  GLADE_HOOKUP_OBJECT (modifiererreur, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (modifiererreur, label75, "label75");
  GLADE_HOOKUP_OBJECT (modifiererreur, button244_cm, "button244_cm");
  GLADE_HOOKUP_OBJECT (modifiererreur, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (modifiererreur, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (modifiererreur, image36, "image36");
  GLADE_HOOKUP_OBJECT (modifiererreur, label76, "label76");

  return modifiererreur;
}

