/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Foyer_ESPRIT;
  GtkWidget *Ajouter_Foyer;
  GtkWidget *Modifier_Foyer;
  GtkWidget *Supprimer_Foyer;
  GtkWidget *Afficher_Foyer;
  GtkWidget *Rechercher_Foyer;
  GtkWidget *gestiondesmenusdelasemaine;
  GtkWidget *ajouterunmenu;
  GtkWidget *rechercherunmenu;
  GtkWidget *meilleurmenudelasemaine;
  GtkWidget *supprimerunmenu;
  GtkWidget *modifierunmenu;
  GtkWidget *idajoutnondisponible;
  GtkWidget *supprimererreur;
  GtkWidget *verifierlamodification;
  GtkWidget *modifiererreur;
  GtkWidget *rupture_stock;
  GtkWidget *affichage_produit;
  GtkWidget *ajout_produit;
  GtkWidget *suppression_produit;
  GtkWidget *modification_produit;
  GtkWidget *recherche_produit;
  GtkWidget *existence;
  GtkWidget *hb_espace_admin;
  GtkWidget *hb_ajouter;
  GtkWidget *hb_gestion;
  GtkWidget *hb_suprrimer;
  GtkWidget *hb_modifier;
  GtkWidget *hb_chercher_un_utilisateur;
  GtkWidget *hb_first_window;
  GtkWidget *hb_dashboard;
  GtkWidget *window2_aj_gm;
  GtkWidget *window3_rech_gm;
  GtkWidget *window5_supp_gm;
  GtkWidget *window7_ser_recl;
  GtkWidget *window6_aff_gm;
  GtkWidget *window4_mod_gm;
  GtkWidget *window1_acc_gm;
  GtkWidget *dashboard;
  GtkWidget *aj;
  GtkWidget *mod;
  GtkWidget *af;
  GtkWidget *cherch;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Foyer_ESPRIT = create_Foyer_ESPRIT ();
  gtk_widget_show (Foyer_ESPRIT);
  gestiondesmenusdelasemaine = create_gestiondesmenusdelasemaine ();
  gtk_widget_show (gestiondesmenusdelasemaine);
  affichage_produit = create_affichage_produit ();
  gtk_widget_show (affichage_produit);
  hb_espace_admin = create_hb_espace_admin ();
  gtk_widget_show (hb_espace_admin);
  hb_dashboard = create_hb_dashboard ();
  gtk_widget_show (hb_dashboard);
  window1_acc_gm = create_window1_acc_gm ();
  gtk_widget_show (window1_acc_gm);

  dashboard = create_dashboard ();
  gtk_widget_show (dashboard);
  

  gtk_main ();
  return 0;
}

